// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/qproxy.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueueId_QueueType int32

const (
	QueueId_Standard QueueId_QueueType = 0
	QueueId_Fifo     QueueId_QueueType = 1
)

var QueueId_QueueType_name = map[int32]string{
	0: "Standard",
	1: "Fifo",
}
var QueueId_QueueType_value = map[string]int32{
	"Standard": 0,
	"Fifo":     1,
}

func (x QueueId_QueueType) String() string {
	return proto.EnumName(QueueId_QueueType_name, int32(x))
}
func (QueueId_QueueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{0, 0}
}

type QueueId struct {
	Namespace            string            `protobuf:"bytes,1,opt,name=Namespace,proto3" json:"Namespace"`
	Name                 string            `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	Type                 QueueId_QueueType `protobuf:"varint,3,opt,name=Type,proto3,enum=rpc.QueueId_QueueType" json:"Type"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueueId) Reset()         { *m = QueueId{} }
func (m *QueueId) String() string { return proto.CompactTextString(m) }
func (*QueueId) ProtoMessage()    {}
func (*QueueId) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{0}
}
func (m *QueueId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueId.Unmarshal(m, b)
}
func (m *QueueId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueId.Marshal(b, m, deterministic)
}
func (dst *QueueId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueId.Merge(dst, src)
}
func (m *QueueId) XXX_Size() int {
	return xxx_messageInfo_QueueId.Size(m)
}
func (m *QueueId) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueId.DiscardUnknown(m)
}

var xxx_messageInfo_QueueId proto.InternalMessageInfo

func (m *QueueId) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *QueueId) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QueueId) GetType() QueueId_QueueType {
	if m != nil {
		return m.Type
	}
	return QueueId_Standard
}

type ListQueuesRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=Namespace,proto3" json:"Namespace"`
	Filter               string   `protobuf:"bytes,2,opt,name=Filter,proto3" json:"Filter"`
	RPCTimeout           int64    `protobuf:"varint,100,opt,name=RPCTimeout,proto3" json:"RPCTimeout"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListQueuesRequest) Reset()         { *m = ListQueuesRequest{} }
func (m *ListQueuesRequest) String() string { return proto.CompactTextString(m) }
func (*ListQueuesRequest) ProtoMessage()    {}
func (*ListQueuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{1}
}
func (m *ListQueuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQueuesRequest.Unmarshal(m, b)
}
func (m *ListQueuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQueuesRequest.Marshal(b, m, deterministic)
}
func (dst *ListQueuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQueuesRequest.Merge(dst, src)
}
func (m *ListQueuesRequest) XXX_Size() int {
	return xxx_messageInfo_ListQueuesRequest.Size(m)
}
func (m *ListQueuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQueuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListQueuesRequest proto.InternalMessageInfo

func (m *ListQueuesRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListQueuesRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListQueuesRequest) GetRPCTimeout() int64 {
	if m != nil {
		return m.RPCTimeout
	}
	return 0
}

type ListQueuesResponse struct {
	Queues               []*QueueId `protobuf:"bytes,1,rep,name=Queues,proto3" json:"Queues"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListQueuesResponse) Reset()         { *m = ListQueuesResponse{} }
func (m *ListQueuesResponse) String() string { return proto.CompactTextString(m) }
func (*ListQueuesResponse) ProtoMessage()    {}
func (*ListQueuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{2}
}
func (m *ListQueuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQueuesResponse.Unmarshal(m, b)
}
func (m *ListQueuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQueuesResponse.Marshal(b, m, deterministic)
}
func (dst *ListQueuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQueuesResponse.Merge(dst, src)
}
func (m *ListQueuesResponse) XXX_Size() int {
	return xxx_messageInfo_ListQueuesResponse.Size(m)
}
func (m *ListQueuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQueuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListQueuesResponse proto.InternalMessageInfo

func (m *ListQueuesResponse) GetQueues() []*QueueId {
	if m != nil {
		return m.Queues
	}
	return nil
}

type GetQueueRequest struct {
	Id                   *QueueId `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id"`
	RPCTimeout           int64    `protobuf:"varint,100,opt,name=RPCTimeout,proto3" json:"RPCTimeout"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQueueRequest) Reset()         { *m = GetQueueRequest{} }
func (m *GetQueueRequest) String() string { return proto.CompactTextString(m) }
func (*GetQueueRequest) ProtoMessage()    {}
func (*GetQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{3}
}
func (m *GetQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQueueRequest.Unmarshal(m, b)
}
func (m *GetQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQueueRequest.Marshal(b, m, deterministic)
}
func (dst *GetQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQueueRequest.Merge(dst, src)
}
func (m *GetQueueRequest) XXX_Size() int {
	return xxx_messageInfo_GetQueueRequest.Size(m)
}
func (m *GetQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQueueRequest proto.InternalMessageInfo

func (m *GetQueueRequest) GetId() *QueueId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GetQueueRequest) GetRPCTimeout() int64 {
	if m != nil {
		return m.RPCTimeout
	}
	return 0
}

type GetQueueResponse struct {
	Attributes           map[string]string `protobuf:"bytes,1,rep,name=Attributes,proto3" json:"Attributes" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetQueueResponse) Reset()         { *m = GetQueueResponse{} }
func (m *GetQueueResponse) String() string { return proto.CompactTextString(m) }
func (*GetQueueResponse) ProtoMessage()    {}
func (*GetQueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{4}
}
func (m *GetQueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQueueResponse.Unmarshal(m, b)
}
func (m *GetQueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQueueResponse.Marshal(b, m, deterministic)
}
func (dst *GetQueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQueueResponse.Merge(dst, src)
}
func (m *GetQueueResponse) XXX_Size() int {
	return xxx_messageInfo_GetQueueResponse.Size(m)
}
func (m *GetQueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetQueueResponse proto.InternalMessageInfo

func (m *GetQueueResponse) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type CreateQueueRequest struct {
	Id                   *QueueId          `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id"`
	Attributes           map[string]string `protobuf:"bytes,2,rep,name=Attributes,proto3" json:"Attributes" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RPCTimeout           int64             `protobuf:"varint,100,opt,name=RPCTimeout,proto3" json:"RPCTimeout"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateQueueRequest) Reset()         { *m = CreateQueueRequest{} }
func (m *CreateQueueRequest) String() string { return proto.CompactTextString(m) }
func (*CreateQueueRequest) ProtoMessage()    {}
func (*CreateQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{5}
}
func (m *CreateQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQueueRequest.Unmarshal(m, b)
}
func (m *CreateQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQueueRequest.Marshal(b, m, deterministic)
}
func (dst *CreateQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQueueRequest.Merge(dst, src)
}
func (m *CreateQueueRequest) XXX_Size() int {
	return xxx_messageInfo_CreateQueueRequest.Size(m)
}
func (m *CreateQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQueueRequest proto.InternalMessageInfo

func (m *CreateQueueRequest) GetId() *QueueId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CreateQueueRequest) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *CreateQueueRequest) GetRPCTimeout() int64 {
	if m != nil {
		return m.RPCTimeout
	}
	return 0
}

type CreateQueueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateQueueResponse) Reset()         { *m = CreateQueueResponse{} }
func (m *CreateQueueResponse) String() string { return proto.CompactTextString(m) }
func (*CreateQueueResponse) ProtoMessage()    {}
func (*CreateQueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{6}
}
func (m *CreateQueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQueueResponse.Unmarshal(m, b)
}
func (m *CreateQueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQueueResponse.Marshal(b, m, deterministic)
}
func (dst *CreateQueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQueueResponse.Merge(dst, src)
}
func (m *CreateQueueResponse) XXX_Size() int {
	return xxx_messageInfo_CreateQueueResponse.Size(m)
}
func (m *CreateQueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQueueResponse proto.InternalMessageInfo

type DeleteQueueRequest struct {
	Id                   *QueueId `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id"`
	RPCTimeout           int64    `protobuf:"varint,100,opt,name=RPCTimeout,proto3" json:"RPCTimeout"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteQueueRequest) Reset()         { *m = DeleteQueueRequest{} }
func (m *DeleteQueueRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteQueueRequest) ProtoMessage()    {}
func (*DeleteQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{7}
}
func (m *DeleteQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteQueueRequest.Unmarshal(m, b)
}
func (m *DeleteQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteQueueRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteQueueRequest.Merge(dst, src)
}
func (m *DeleteQueueRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteQueueRequest.Size(m)
}
func (m *DeleteQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteQueueRequest proto.InternalMessageInfo

func (m *DeleteQueueRequest) GetId() *QueueId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DeleteQueueRequest) GetRPCTimeout() int64 {
	if m != nil {
		return m.RPCTimeout
	}
	return 0
}

type DeleteQueueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteQueueResponse) Reset()         { *m = DeleteQueueResponse{} }
func (m *DeleteQueueResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteQueueResponse) ProtoMessage()    {}
func (*DeleteQueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{8}
}
func (m *DeleteQueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteQueueResponse.Unmarshal(m, b)
}
func (m *DeleteQueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteQueueResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteQueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteQueueResponse.Merge(dst, src)
}
func (m *DeleteQueueResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteQueueResponse.Size(m)
}
func (m *DeleteQueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteQueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteQueueResponse proto.InternalMessageInfo

type ModifyQueueRequest struct {
	Id                   *QueueId          `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id"`
	Attributes           map[string]string `protobuf:"bytes,2,rep,name=Attributes,proto3" json:"Attributes" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RPCTimeout           int64             `protobuf:"varint,100,opt,name=RPCTimeout,proto3" json:"RPCTimeout"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ModifyQueueRequest) Reset()         { *m = ModifyQueueRequest{} }
func (m *ModifyQueueRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyQueueRequest) ProtoMessage()    {}
func (*ModifyQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{9}
}
func (m *ModifyQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyQueueRequest.Unmarshal(m, b)
}
func (m *ModifyQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyQueueRequest.Marshal(b, m, deterministic)
}
func (dst *ModifyQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyQueueRequest.Merge(dst, src)
}
func (m *ModifyQueueRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyQueueRequest.Size(m)
}
func (m *ModifyQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyQueueRequest proto.InternalMessageInfo

func (m *ModifyQueueRequest) GetId() *QueueId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ModifyQueueRequest) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *ModifyQueueRequest) GetRPCTimeout() int64 {
	if m != nil {
		return m.RPCTimeout
	}
	return 0
}

type ModifyQueueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyQueueResponse) Reset()         { *m = ModifyQueueResponse{} }
func (m *ModifyQueueResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyQueueResponse) ProtoMessage()    {}
func (*ModifyQueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{10}
}
func (m *ModifyQueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyQueueResponse.Unmarshal(m, b)
}
func (m *ModifyQueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyQueueResponse.Marshal(b, m, deterministic)
}
func (dst *ModifyQueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyQueueResponse.Merge(dst, src)
}
func (m *ModifyQueueResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyQueueResponse.Size(m)
}
func (m *ModifyQueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyQueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyQueueResponse proto.InternalMessageInfo

type PurgeQueueRequest struct {
	Id                   *QueueId `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id"`
	RPCTimeout           int64    `protobuf:"varint,100,opt,name=RPCTimeout,proto3" json:"RPCTimeout"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PurgeQueueRequest) Reset()         { *m = PurgeQueueRequest{} }
func (m *PurgeQueueRequest) String() string { return proto.CompactTextString(m) }
func (*PurgeQueueRequest) ProtoMessage()    {}
func (*PurgeQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{11}
}
func (m *PurgeQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurgeQueueRequest.Unmarshal(m, b)
}
func (m *PurgeQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurgeQueueRequest.Marshal(b, m, deterministic)
}
func (dst *PurgeQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurgeQueueRequest.Merge(dst, src)
}
func (m *PurgeQueueRequest) XXX_Size() int {
	return xxx_messageInfo_PurgeQueueRequest.Size(m)
}
func (m *PurgeQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PurgeQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PurgeQueueRequest proto.InternalMessageInfo

func (m *PurgeQueueRequest) GetId() *QueueId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PurgeQueueRequest) GetRPCTimeout() int64 {
	if m != nil {
		return m.RPCTimeout
	}
	return 0
}

type PurgeQueueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PurgeQueueResponse) Reset()         { *m = PurgeQueueResponse{} }
func (m *PurgeQueueResponse) String() string { return proto.CompactTextString(m) }
func (*PurgeQueueResponse) ProtoMessage()    {}
func (*PurgeQueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{12}
}
func (m *PurgeQueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurgeQueueResponse.Unmarshal(m, b)
}
func (m *PurgeQueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurgeQueueResponse.Marshal(b, m, deterministic)
}
func (dst *PurgeQueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurgeQueueResponse.Merge(dst, src)
}
func (m *PurgeQueueResponse) XXX_Size() int {
	return xxx_messageInfo_PurgeQueueResponse.Size(m)
}
func (m *PurgeQueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PurgeQueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PurgeQueueResponse proto.InternalMessageInfo

type MessageReceipt struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReceipt) Reset()         { *m = MessageReceipt{} }
func (m *MessageReceipt) String() string { return proto.CompactTextString(m) }
func (*MessageReceipt) ProtoMessage()    {}
func (*MessageReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{13}
}
func (m *MessageReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReceipt.Unmarshal(m, b)
}
func (m *MessageReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReceipt.Marshal(b, m, deterministic)
}
func (dst *MessageReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReceipt.Merge(dst, src)
}
func (m *MessageReceipt) XXX_Size() int {
	return xxx_messageInfo_MessageReceipt.Size(m)
}
func (m *MessageReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReceipt proto.InternalMessageInfo

func (m *MessageReceipt) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageReceipt) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type FailedPublish struct {
	Index                int64    `protobuf:"varint,1,opt,name=Index,proto3" json:"Index"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailedPublish) Reset()         { *m = FailedPublish{} }
func (m *FailedPublish) String() string { return proto.CompactTextString(m) }
func (*FailedPublish) ProtoMessage()    {}
func (*FailedPublish) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{14}
}
func (m *FailedPublish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailedPublish.Unmarshal(m, b)
}
func (m *FailedPublish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailedPublish.Marshal(b, m, deterministic)
}
func (dst *FailedPublish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailedPublish.Merge(dst, src)
}
func (m *FailedPublish) XXX_Size() int {
	return xxx_messageInfo_FailedPublish.Size(m)
}
func (m *FailedPublish) XXX_DiscardUnknown() {
	xxx_messageInfo_FailedPublish.DiscardUnknown(m)
}

var xxx_messageInfo_FailedPublish proto.InternalMessageInfo

func (m *FailedPublish) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *FailedPublish) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type Message struct {
	Data                 string            `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data"`
	Attributes           map[string]string `protobuf:"bytes,2,rep,name=Attributes,proto3" json:"Attributes" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Receipt              *MessageReceipt   `protobuf:"bytes,100,opt,name=Receipt,proto3" json:"Receipt"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{15}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Message) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Message) GetReceipt() *MessageReceipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

type AckMessagesRequest struct {
	QueueId              *QueueId          `protobuf:"bytes,1,opt,name=QueueId,proto3" json:"QueueId"`
	Receipts             []*MessageReceipt `protobuf:"bytes,2,rep,name=Receipts,proto3" json:"Receipts"`
	RPCTimeout           int64             `protobuf:"varint,100,opt,name=RPCTimeout,proto3" json:"RPCTimeout"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AckMessagesRequest) Reset()         { *m = AckMessagesRequest{} }
func (m *AckMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*AckMessagesRequest) ProtoMessage()    {}
func (*AckMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{16}
}
func (m *AckMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckMessagesRequest.Unmarshal(m, b)
}
func (m *AckMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckMessagesRequest.Marshal(b, m, deterministic)
}
func (dst *AckMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckMessagesRequest.Merge(dst, src)
}
func (m *AckMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_AckMessagesRequest.Size(m)
}
func (m *AckMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AckMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AckMessagesRequest proto.InternalMessageInfo

func (m *AckMessagesRequest) GetQueueId() *QueueId {
	if m != nil {
		return m.QueueId
	}
	return nil
}

func (m *AckMessagesRequest) GetReceipts() []*MessageReceipt {
	if m != nil {
		return m.Receipts
	}
	return nil
}

func (m *AckMessagesRequest) GetRPCTimeout() int64 {
	if m != nil {
		return m.RPCTimeout
	}
	return 0
}

type AckMessagesResponse struct {
	// Return the receipts that failed to ack
	Failed               []*MessageReceipt `protobuf:"bytes,1,rep,name=Failed,proto3" json:"Failed"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AckMessagesResponse) Reset()         { *m = AckMessagesResponse{} }
func (m *AckMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*AckMessagesResponse) ProtoMessage()    {}
func (*AckMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{17}
}
func (m *AckMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckMessagesResponse.Unmarshal(m, b)
}
func (m *AckMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckMessagesResponse.Marshal(b, m, deterministic)
}
func (dst *AckMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckMessagesResponse.Merge(dst, src)
}
func (m *AckMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_AckMessagesResponse.Size(m)
}
func (m *AckMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckMessagesResponse proto.InternalMessageInfo

func (m *AckMessagesResponse) GetFailed() []*MessageReceipt {
	if m != nil {
		return m.Failed
	}
	return nil
}

type GetMessagesRequest struct {
	QueueId *QueueId `protobuf:"bytes,1,opt,name=QueueId,proto3" json:"QueueId"`
	// How long to poll for up to MaxMessages messages. 0 implies return immediately
	LongPollSeconds      int64    `protobuf:"varint,2,opt,name=LongPollSeconds,proto3" json:"LongPollSeconds"`
	MaxMessages          int64    `protobuf:"varint,3,opt,name=MaxMessages,proto3" json:"MaxMessages"`
	AckDeadlineSeconds   int64    `protobuf:"varint,4,opt,name=AckDeadlineSeconds,proto3" json:"AckDeadlineSeconds"`
	RPCTimeout           int64    `protobuf:"varint,100,opt,name=RPCTimeout,proto3" json:"RPCTimeout"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessagesRequest) Reset()         { *m = GetMessagesRequest{} }
func (m *GetMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessagesRequest) ProtoMessage()    {}
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{18}
}
func (m *GetMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesRequest.Unmarshal(m, b)
}
func (m *GetMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesRequest.Marshal(b, m, deterministic)
}
func (dst *GetMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesRequest.Merge(dst, src)
}
func (m *GetMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessagesRequest.Size(m)
}
func (m *GetMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesRequest proto.InternalMessageInfo

func (m *GetMessagesRequest) GetQueueId() *QueueId {
	if m != nil {
		return m.QueueId
	}
	return nil
}

func (m *GetMessagesRequest) GetLongPollSeconds() int64 {
	if m != nil {
		return m.LongPollSeconds
	}
	return 0
}

func (m *GetMessagesRequest) GetMaxMessages() int64 {
	if m != nil {
		return m.MaxMessages
	}
	return 0
}

func (m *GetMessagesRequest) GetAckDeadlineSeconds() int64 {
	if m != nil {
		return m.AckDeadlineSeconds
	}
	return 0
}

func (m *GetMessagesRequest) GetRPCTimeout() int64 {
	if m != nil {
		return m.RPCTimeout
	}
	return 0
}

type GetMessagesResponse struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=Messages,proto3" json:"Messages"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetMessagesResponse) Reset()         { *m = GetMessagesResponse{} }
func (m *GetMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMessagesResponse) ProtoMessage()    {}
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{19}
}
func (m *GetMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesResponse.Unmarshal(m, b)
}
func (m *GetMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesResponse.Marshal(b, m, deterministic)
}
func (dst *GetMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesResponse.Merge(dst, src)
}
func (m *GetMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMessagesResponse.Size(m)
}
func (m *GetMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesResponse proto.InternalMessageInfo

func (m *GetMessagesResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type PublishMessagesRequest struct {
	QueueId              *QueueId   `protobuf:"bytes,1,opt,name=QueueId,proto3" json:"QueueId"`
	Messages             []*Message `protobuf:"bytes,2,rep,name=Messages,proto3" json:"Messages"`
	RPCTimeout           int64      `protobuf:"varint,100,opt,name=RPCTimeout,proto3" json:"RPCTimeout"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PublishMessagesRequest) Reset()         { *m = PublishMessagesRequest{} }
func (m *PublishMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*PublishMessagesRequest) ProtoMessage()    {}
func (*PublishMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{20}
}
func (m *PublishMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishMessagesRequest.Unmarshal(m, b)
}
func (m *PublishMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishMessagesRequest.Marshal(b, m, deterministic)
}
func (dst *PublishMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishMessagesRequest.Merge(dst, src)
}
func (m *PublishMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_PublishMessagesRequest.Size(m)
}
func (m *PublishMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishMessagesRequest proto.InternalMessageInfo

func (m *PublishMessagesRequest) GetQueueId() *QueueId {
	if m != nil {
		return m.QueueId
	}
	return nil
}

func (m *PublishMessagesRequest) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *PublishMessagesRequest) GetRPCTimeout() int64 {
	if m != nil {
		return m.RPCTimeout
	}
	return 0
}

type PublishMessagesResponse struct {
	// Return the indexes of the messages that failed to send
	Failed               []*FailedPublish `protobuf:"bytes,1,rep,name=Failed,proto3" json:"Failed"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PublishMessagesResponse) Reset()         { *m = PublishMessagesResponse{} }
func (m *PublishMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*PublishMessagesResponse) ProtoMessage()    {}
func (*PublishMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{21}
}
func (m *PublishMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishMessagesResponse.Unmarshal(m, b)
}
func (m *PublishMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishMessagesResponse.Marshal(b, m, deterministic)
}
func (dst *PublishMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishMessagesResponse.Merge(dst, src)
}
func (m *PublishMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_PublishMessagesResponse.Size(m)
}
func (m *PublishMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishMessagesResponse proto.InternalMessageInfo

func (m *PublishMessagesResponse) GetFailed() []*FailedPublish {
	if m != nil {
		return m.Failed
	}
	return nil
}

type ModifyAckDeadlineRequest struct {
	QueueId              *QueueId        `protobuf:"bytes,1,opt,name=QueueId,proto3" json:"QueueId"`
	Receipt              *MessageReceipt `protobuf:"bytes,2,opt,name=Receipt,proto3" json:"Receipt"`
	AckDeadlineSeconds   int64           `protobuf:"varint,3,opt,name=AckDeadlineSeconds,proto3" json:"AckDeadlineSeconds"`
	RPCTimeout           int64           `protobuf:"varint,100,opt,name=RPCTimeout,proto3" json:"RPCTimeout"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ModifyAckDeadlineRequest) Reset()         { *m = ModifyAckDeadlineRequest{} }
func (m *ModifyAckDeadlineRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyAckDeadlineRequest) ProtoMessage()    {}
func (*ModifyAckDeadlineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{22}
}
func (m *ModifyAckDeadlineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyAckDeadlineRequest.Unmarshal(m, b)
}
func (m *ModifyAckDeadlineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyAckDeadlineRequest.Marshal(b, m, deterministic)
}
func (dst *ModifyAckDeadlineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyAckDeadlineRequest.Merge(dst, src)
}
func (m *ModifyAckDeadlineRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyAckDeadlineRequest.Size(m)
}
func (m *ModifyAckDeadlineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyAckDeadlineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyAckDeadlineRequest proto.InternalMessageInfo

func (m *ModifyAckDeadlineRequest) GetQueueId() *QueueId {
	if m != nil {
		return m.QueueId
	}
	return nil
}

func (m *ModifyAckDeadlineRequest) GetReceipt() *MessageReceipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

func (m *ModifyAckDeadlineRequest) GetAckDeadlineSeconds() int64 {
	if m != nil {
		return m.AckDeadlineSeconds
	}
	return 0
}

func (m *ModifyAckDeadlineRequest) GetRPCTimeout() int64 {
	if m != nil {
		return m.RPCTimeout
	}
	return 0
}

type ModifyAckDeadlineResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyAckDeadlineResponse) Reset()         { *m = ModifyAckDeadlineResponse{} }
func (m *ModifyAckDeadlineResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyAckDeadlineResponse) ProtoMessage()    {}
func (*ModifyAckDeadlineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{23}
}
func (m *ModifyAckDeadlineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyAckDeadlineResponse.Unmarshal(m, b)
}
func (m *ModifyAckDeadlineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyAckDeadlineResponse.Marshal(b, m, deterministic)
}
func (dst *ModifyAckDeadlineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyAckDeadlineResponse.Merge(dst, src)
}
func (m *ModifyAckDeadlineResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyAckDeadlineResponse.Size(m)
}
func (m *ModifyAckDeadlineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyAckDeadlineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyAckDeadlineResponse proto.InternalMessageInfo

type HealthcheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthcheckRequest) Reset()         { *m = HealthcheckRequest{} }
func (m *HealthcheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthcheckRequest) ProtoMessage()    {}
func (*HealthcheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{24}
}
func (m *HealthcheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthcheckRequest.Unmarshal(m, b)
}
func (m *HealthcheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthcheckRequest.Marshal(b, m, deterministic)
}
func (dst *HealthcheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthcheckRequest.Merge(dst, src)
}
func (m *HealthcheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthcheckRequest.Size(m)
}
func (m *HealthcheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthcheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthcheckRequest proto.InternalMessageInfo

type HealthcheckResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthcheckResponse) Reset()         { *m = HealthcheckResponse{} }
func (m *HealthcheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthcheckResponse) ProtoMessage()    {}
func (*HealthcheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_qproxy_6cb6bea1f50f92ce, []int{25}
}
func (m *HealthcheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthcheckResponse.Unmarshal(m, b)
}
func (m *HealthcheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthcheckResponse.Marshal(b, m, deterministic)
}
func (dst *HealthcheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthcheckResponse.Merge(dst, src)
}
func (m *HealthcheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthcheckResponse.Size(m)
}
func (m *HealthcheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthcheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthcheckResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueueId)(nil), "rpc.QueueId")
	proto.RegisterType((*ListQueuesRequest)(nil), "rpc.ListQueuesRequest")
	proto.RegisterType((*ListQueuesResponse)(nil), "rpc.ListQueuesResponse")
	proto.RegisterType((*GetQueueRequest)(nil), "rpc.GetQueueRequest")
	proto.RegisterType((*GetQueueResponse)(nil), "rpc.GetQueueResponse")
	proto.RegisterMapType((map[string]string)(nil), "rpc.GetQueueResponse.AttributesEntry")
	proto.RegisterType((*CreateQueueRequest)(nil), "rpc.CreateQueueRequest")
	proto.RegisterMapType((map[string]string)(nil), "rpc.CreateQueueRequest.AttributesEntry")
	proto.RegisterType((*CreateQueueResponse)(nil), "rpc.CreateQueueResponse")
	proto.RegisterType((*DeleteQueueRequest)(nil), "rpc.DeleteQueueRequest")
	proto.RegisterType((*DeleteQueueResponse)(nil), "rpc.DeleteQueueResponse")
	proto.RegisterType((*ModifyQueueRequest)(nil), "rpc.ModifyQueueRequest")
	proto.RegisterMapType((map[string]string)(nil), "rpc.ModifyQueueRequest.AttributesEntry")
	proto.RegisterType((*ModifyQueueResponse)(nil), "rpc.ModifyQueueResponse")
	proto.RegisterType((*PurgeQueueRequest)(nil), "rpc.PurgeQueueRequest")
	proto.RegisterType((*PurgeQueueResponse)(nil), "rpc.PurgeQueueResponse")
	proto.RegisterType((*MessageReceipt)(nil), "rpc.MessageReceipt")
	proto.RegisterType((*FailedPublish)(nil), "rpc.FailedPublish")
	proto.RegisterType((*Message)(nil), "rpc.Message")
	proto.RegisterMapType((map[string]string)(nil), "rpc.Message.AttributesEntry")
	proto.RegisterType((*AckMessagesRequest)(nil), "rpc.AckMessagesRequest")
	proto.RegisterType((*AckMessagesResponse)(nil), "rpc.AckMessagesResponse")
	proto.RegisterType((*GetMessagesRequest)(nil), "rpc.GetMessagesRequest")
	proto.RegisterType((*GetMessagesResponse)(nil), "rpc.GetMessagesResponse")
	proto.RegisterType((*PublishMessagesRequest)(nil), "rpc.PublishMessagesRequest")
	proto.RegisterType((*PublishMessagesResponse)(nil), "rpc.PublishMessagesResponse")
	proto.RegisterType((*ModifyAckDeadlineRequest)(nil), "rpc.ModifyAckDeadlineRequest")
	proto.RegisterType((*ModifyAckDeadlineResponse)(nil), "rpc.ModifyAckDeadlineResponse")
	proto.RegisterType((*HealthcheckRequest)(nil), "rpc.HealthcheckRequest")
	proto.RegisterType((*HealthcheckResponse)(nil), "rpc.HealthcheckResponse")
	proto.RegisterEnum("rpc.QueueId_QueueType", QueueId_QueueType_name, QueueId_QueueType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QProxyClient is the client API for QProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QProxyClient interface {
	ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (QProxy_ListQueuesClient, error)
	GetQueue(ctx context.Context, in *GetQueueRequest, opts ...grpc.CallOption) (*GetQueueResponse, error)
	CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error)
	DeleteQueue(ctx context.Context, in *DeleteQueueRequest, opts ...grpc.CallOption) (*DeleteQueueResponse, error)
	ModifyQueue(ctx context.Context, in *ModifyQueueRequest, opts ...grpc.CallOption) (*ModifyQueueResponse, error)
	PurgeQueue(ctx context.Context, in *PurgeQueueRequest, opts ...grpc.CallOption) (*PurgeQueueResponse, error)
	AckMessages(ctx context.Context, in *AckMessagesRequest, opts ...grpc.CallOption) (*AckMessagesResponse, error)
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	PublishMessages(ctx context.Context, in *PublishMessagesRequest, opts ...grpc.CallOption) (*PublishMessagesResponse, error)
	ModifyAckDeadline(ctx context.Context, in *ModifyAckDeadlineRequest, opts ...grpc.CallOption) (*ModifyAckDeadlineResponse, error)
	Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
}

type qProxyClient struct {
	cc *grpc.ClientConn
}

func NewQProxyClient(cc *grpc.ClientConn) QProxyClient {
	return &qProxyClient{cc}
}

func (c *qProxyClient) ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (QProxy_ListQueuesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_QProxy_serviceDesc.Streams[0], "/rpc.QProxy/ListQueues", opts...)
	if err != nil {
		return nil, err
	}
	x := &qProxyListQueuesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QProxy_ListQueuesClient interface {
	Recv() (*ListQueuesResponse, error)
	grpc.ClientStream
}

type qProxyListQueuesClient struct {
	grpc.ClientStream
}

func (x *qProxyListQueuesClient) Recv() (*ListQueuesResponse, error) {
	m := new(ListQueuesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *qProxyClient) GetQueue(ctx context.Context, in *GetQueueRequest, opts ...grpc.CallOption) (*GetQueueResponse, error) {
	out := new(GetQueueResponse)
	err := c.cc.Invoke(ctx, "/rpc.QProxy/GetQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qProxyClient) CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error) {
	out := new(CreateQueueResponse)
	err := c.cc.Invoke(ctx, "/rpc.QProxy/CreateQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qProxyClient) DeleteQueue(ctx context.Context, in *DeleteQueueRequest, opts ...grpc.CallOption) (*DeleteQueueResponse, error) {
	out := new(DeleteQueueResponse)
	err := c.cc.Invoke(ctx, "/rpc.QProxy/DeleteQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qProxyClient) ModifyQueue(ctx context.Context, in *ModifyQueueRequest, opts ...grpc.CallOption) (*ModifyQueueResponse, error) {
	out := new(ModifyQueueResponse)
	err := c.cc.Invoke(ctx, "/rpc.QProxy/ModifyQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qProxyClient) PurgeQueue(ctx context.Context, in *PurgeQueueRequest, opts ...grpc.CallOption) (*PurgeQueueResponse, error) {
	out := new(PurgeQueueResponse)
	err := c.cc.Invoke(ctx, "/rpc.QProxy/PurgeQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qProxyClient) AckMessages(ctx context.Context, in *AckMessagesRequest, opts ...grpc.CallOption) (*AckMessagesResponse, error) {
	out := new(AckMessagesResponse)
	err := c.cc.Invoke(ctx, "/rpc.QProxy/AckMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qProxyClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, "/rpc.QProxy/GetMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qProxyClient) PublishMessages(ctx context.Context, in *PublishMessagesRequest, opts ...grpc.CallOption) (*PublishMessagesResponse, error) {
	out := new(PublishMessagesResponse)
	err := c.cc.Invoke(ctx, "/rpc.QProxy/PublishMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qProxyClient) ModifyAckDeadline(ctx context.Context, in *ModifyAckDeadlineRequest, opts ...grpc.CallOption) (*ModifyAckDeadlineResponse, error) {
	out := new(ModifyAckDeadlineResponse)
	err := c.cc.Invoke(ctx, "/rpc.QProxy/ModifyAckDeadline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qProxyClient) Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/rpc.QProxy/Healthcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QProxyServer is the server API for QProxy service.
type QProxyServer interface {
	ListQueues(*ListQueuesRequest, QProxy_ListQueuesServer) error
	GetQueue(context.Context, *GetQueueRequest) (*GetQueueResponse, error)
	CreateQueue(context.Context, *CreateQueueRequest) (*CreateQueueResponse, error)
	DeleteQueue(context.Context, *DeleteQueueRequest) (*DeleteQueueResponse, error)
	ModifyQueue(context.Context, *ModifyQueueRequest) (*ModifyQueueResponse, error)
	PurgeQueue(context.Context, *PurgeQueueRequest) (*PurgeQueueResponse, error)
	AckMessages(context.Context, *AckMessagesRequest) (*AckMessagesResponse, error)
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	PublishMessages(context.Context, *PublishMessagesRequest) (*PublishMessagesResponse, error)
	ModifyAckDeadline(context.Context, *ModifyAckDeadlineRequest) (*ModifyAckDeadlineResponse, error)
	Healthcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
}

func RegisterQProxyServer(s *grpc.Server, srv QProxyServer) {
	s.RegisterService(&_QProxy_serviceDesc, srv)
}

func _QProxy_ListQueues_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListQueuesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QProxyServer).ListQueues(m, &qProxyListQueuesServer{stream})
}

type QProxy_ListQueuesServer interface {
	Send(*ListQueuesResponse) error
	grpc.ServerStream
}

type qProxyListQueuesServer struct {
	grpc.ServerStream
}

func (x *qProxyListQueuesServer) Send(m *ListQueuesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _QProxy_GetQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QProxyServer).GetQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.QProxy/GetQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QProxyServer).GetQueue(ctx, req.(*GetQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QProxy_CreateQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QProxyServer).CreateQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.QProxy/CreateQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QProxyServer).CreateQueue(ctx, req.(*CreateQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QProxy_DeleteQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QProxyServer).DeleteQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.QProxy/DeleteQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QProxyServer).DeleteQueue(ctx, req.(*DeleteQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QProxy_ModifyQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QProxyServer).ModifyQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.QProxy/ModifyQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QProxyServer).ModifyQueue(ctx, req.(*ModifyQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QProxy_PurgeQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QProxyServer).PurgeQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.QProxy/PurgeQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QProxyServer).PurgeQueue(ctx, req.(*PurgeQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QProxy_AckMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QProxyServer).AckMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.QProxy/AckMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QProxyServer).AckMessages(ctx, req.(*AckMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QProxy_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QProxyServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.QProxy/GetMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QProxyServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QProxy_PublishMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QProxyServer).PublishMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.QProxy/PublishMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QProxyServer).PublishMessages(ctx, req.(*PublishMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QProxy_ModifyAckDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyAckDeadlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QProxyServer).ModifyAckDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.QProxy/ModifyAckDeadline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QProxyServer).ModifyAckDeadline(ctx, req.(*ModifyAckDeadlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QProxy_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QProxyServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.QProxy/Healthcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QProxyServer).Healthcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QProxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.QProxy",
	HandlerType: (*QProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQueue",
			Handler:    _QProxy_GetQueue_Handler,
		},
		{
			MethodName: "CreateQueue",
			Handler:    _QProxy_CreateQueue_Handler,
		},
		{
			MethodName: "DeleteQueue",
			Handler:    _QProxy_DeleteQueue_Handler,
		},
		{
			MethodName: "ModifyQueue",
			Handler:    _QProxy_ModifyQueue_Handler,
		},
		{
			MethodName: "PurgeQueue",
			Handler:    _QProxy_PurgeQueue_Handler,
		},
		{
			MethodName: "AckMessages",
			Handler:    _QProxy_AckMessages_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _QProxy_GetMessages_Handler,
		},
		{
			MethodName: "PublishMessages",
			Handler:    _QProxy_PublishMessages_Handler,
		},
		{
			MethodName: "ModifyAckDeadline",
			Handler:    _QProxy_ModifyAckDeadline_Handler,
		},
		{
			MethodName: "Healthcheck",
			Handler:    _QProxy_Healthcheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListQueues",
			Handler:       _QProxy_ListQueues_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc/qproxy.proto",
}

func init() { proto.RegisterFile("rpc/qproxy.proto", fileDescriptor_qproxy_6cb6bea1f50f92ce) }

var fileDescriptor_qproxy_6cb6bea1f50f92ce = []byte{
	// 1055 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xcf, 0x6f, 0xe3, 0xc4,
	0x17, 0xff, 0x4e, 0xd2, 0x6f, 0x9a, 0xbe, 0x96, 0x36, 0x9d, 0xf4, 0x47, 0x48, 0x43, 0xc9, 0x1a,
	0x96, 0x8d, 0x82, 0x48, 0xa0, 0x5c, 0x50, 0x04, 0x42, 0xcb, 0xf6, 0x07, 0x91, 0xb6, 0x90, 0x7a,
	0x57, 0xe2, 0x88, 0xa6, 0xf6, 0x6c, 0x6a, 0xc5, 0xb5, 0x5d, 0x7b, 0xb2, 0x6a, 0xc4, 0x8d, 0x23,
	0x82, 0x13, 0x17, 0xfe, 0x1d, 0x8e, 0x9c, 0xb9, 0x20, 0xce, 0xfc, 0x0b, 0xdc, 0x91, 0xc7, 0x2f,
	0xce, 0x38, 0x9e, 0x36, 0xb4, 0xbb, 0x12, 0xa7, 0xda, 0x33, 0x1f, 0xbf, 0xcf, 0xfb, 0x7c, 0x5e,
	0xe6, 0xbd, 0x29, 0x54, 0xc2, 0xc0, 0xea, 0x5e, 0x05, 0xa1, 0x7f, 0x3d, 0xe9, 0x04, 0xa1, 0x2f,
	0x7c, 0x5a, 0x0c, 0x03, 0xab, 0xde, 0x18, 0xfa, 0xfe, 0xd0, 0xe5, 0x5d, 0x16, 0x38, 0x5d, 0xe6,
	0x79, 0xbe, 0x60, 0xc2, 0xf1, 0xbd, 0x28, 0x81, 0x18, 0x3f, 0x12, 0x58, 0x3e, 0x1b, 0xf3, 0x31,
	0xef, 0xdb, 0xb4, 0x01, 0x2b, 0x5f, 0xb1, 0x4b, 0x1e, 0x05, 0xcc, 0xe2, 0x35, 0xd2, 0x24, 0xad,
	0x15, 0x73, 0xb6, 0x40, 0x29, 0x2c, 0xc5, 0x2f, 0xb5, 0x82, 0xdc, 0x90, 0xcf, 0xb4, 0x0d, 0x4b,
	0xcf, 0x27, 0x01, 0xaf, 0x15, 0x9b, 0xa4, 0xb5, 0x7e, 0xb0, 0xd3, 0x09, 0x03, 0xab, 0x83, 0xd1,
	0x92, 0xbf, 0xf1, 0xae, 0x29, 0x31, 0xc6, 0x3b, 0xb0, 0x92, 0x2e, 0xd1, 0x35, 0x28, 0x3f, 0x13,
	0xcc, 0xb3, 0x59, 0x68, 0x57, 0xfe, 0x47, 0xcb, 0xb0, 0x74, 0xec, 0xbc, 0xf0, 0x2b, 0xc4, 0x70,
	0x60, 0xf3, 0xa9, 0x13, 0x09, 0x09, 0x8c, 0x4c, 0x7e, 0x35, 0xe6, 0x91, 0x58, 0x90, 0xd7, 0x0e,
	0x94, 0x8e, 0x1d, 0x57, 0xf0, 0x10, 0x33, 0xc3, 0x37, 0xba, 0x0f, 0x60, 0x0e, 0x9e, 0x3c, 0x77,
	0x2e, 0xb9, 0x3f, 0x16, 0x35, 0xbb, 0x49, 0x5a, 0x45, 0x53, 0x59, 0x31, 0x7a, 0x40, 0x55, 0xaa,
	0x28, 0xf0, 0xbd, 0x88, 0xd3, 0x77, 0xa1, 0x94, 0xac, 0xd4, 0x48, 0xb3, 0xd8, 0x5a, 0x3d, 0x58,
	0x53, 0x35, 0x99, 0xb8, 0x67, 0x7c, 0x0d, 0x1b, 0x27, 0x3c, 0xf9, 0x74, 0x96, 0x64, 0xa1, 0x6f,
	0xcb, 0xec, 0xe6, 0x3f, 0x2a, 0xf4, 0xed, 0x85, 0xc9, 0xfc, 0x42, 0xa0, 0x32, 0x8b, 0x88, 0xb9,
	0x1c, 0x01, 0x3c, 0x16, 0x22, 0x74, 0xce, 0xc7, 0x22, 0xcd, 0xe7, 0xa1, 0x0c, 0x3d, 0x0f, 0xed,
	0xcc, 0x70, 0x47, 0x9e, 0x08, 0x27, 0xa6, 0xf2, 0x61, 0xfd, 0x33, 0xd8, 0x98, 0xdb, 0xa6, 0x15,
	0x28, 0x8e, 0xf8, 0x04, 0xbd, 0x8c, 0x1f, 0xe9, 0x16, 0xfc, 0xff, 0x25, 0x73, 0xc7, 0xd3, 0xf2,
	0x26, 0x2f, 0xbd, 0xc2, 0x27, 0xc4, 0xf8, 0x93, 0x00, 0x7d, 0x12, 0x72, 0x26, 0xf8, 0x1d, 0xf4,
	0x9e, 0x64, 0x52, 0x2f, 0xc8, 0xd4, 0x1f, 0x49, 0x54, 0x3e, 0xd4, 0x6d, 0xc9, 0x2f, 0x32, 0xee,
	0x55, 0xc5, 0x6d, 0x43, 0x35, 0x93, 0x50, 0x62, 0xa7, 0x61, 0x02, 0x3d, 0xe4, 0x2e, 0xbf, 0x93,
	0xe4, 0x45, 0x25, 0xde, 0x86, 0x6a, 0x26, 0x26, 0x52, 0xc5, 0xf6, 0x9e, 0xfa, 0xb6, 0xf3, 0x62,
	0xf2, 0x5a, 0xec, 0xcd, 0x87, 0xfa, 0x8f, 0xed, 0xcd, 0x24, 0x84, 0x9a, 0xcf, 0x60, 0x73, 0x30,
	0x0e, 0x87, 0xaf, 0xd3, 0xdd, 0x2d, 0xa0, 0x6a, 0x48, 0x24, 0x3a, 0x84, 0xf5, 0x53, 0x1e, 0x45,
	0x6c, 0xc8, 0x4d, 0x6e, 0x71, 0x27, 0x10, 0x74, 0x3d, 0x65, 0x59, 0x91, 0x71, 0x0d, 0x58, 0x3b,
	0x0a, 0x43, 0x3f, 0x44, 0x18, 0x4a, 0xc8, 0xac, 0x19, 0x7d, 0x78, 0xe3, 0x98, 0x39, 0x2e, 0xb7,
	0x07, 0xe3, 0x73, 0xd7, 0x89, 0x2e, 0x62, 0xc1, 0x7d, 0xcf, 0xe6, 0xd7, 0x32, 0x4e, 0xd1, 0x4c,
	0x5e, 0xfe, 0x55, 0xa8, 0xdf, 0x08, 0x2c, 0xe3, 0x73, 0xdc, 0x50, 0x0f, 0x99, 0x60, 0x98, 0x8c,
	0x7c, 0xa6, 0x9f, 0x6a, 0x0a, 0xdb, 0x48, 0x0a, 0x9b, 0x7c, 0x75, 0x6b, 0x35, 0x3f, 0x80, 0x65,
	0xd4, 0x29, 0x1d, 0x5a, 0x3d, 0xa8, 0xaa, 0x9f, 0xe2, 0x96, 0x39, 0xc5, 0xbc, 0x6a, 0x71, 0x7f,
	0x22, 0x40, 0x1f, 0x5b, 0x23, 0x8c, 0x9e, 0x76, 0xeb, 0xf7, 0xd2, 0x81, 0xa2, 0x2d, 0x66, 0x3a,
	0x6d, 0xba, 0x50, 0xc6, 0x44, 0xa6, 0x42, 0xb5, 0xd9, 0xa6, 0xa0, 0x85, 0x3f, 0x81, 0x2f, 0xa0,
	0x9a, 0x49, 0x07, 0xbb, 0xe8, 0xfb, 0x50, 0x4a, 0xaa, 0x87, 0x1d, 0x54, 0xcb, 0x82, 0x10, 0xe3,
	0x0f, 0x02, 0xf4, 0x84, 0x8b, 0xfb, 0x6a, 0x6a, 0xc1, 0xc6, 0x53, 0xdf, 0x1b, 0x0e, 0x7c, 0xd7,
	0x7d, 0xc6, 0x2d, 0xdf, 0xb3, 0x23, 0x69, 0x5b, 0xd1, 0x9c, 0x5f, 0xa6, 0x4d, 0x58, 0x3d, 0x65,
	0xd7, 0x53, 0x1e, 0x39, 0x40, 0x8b, 0xa6, 0xba, 0x44, 0x3b, 0xd2, 0xdd, 0x43, 0xce, 0x6c, 0xd7,
	0xf1, 0xf8, 0x34, 0xdc, 0x92, 0x04, 0x6a, 0x76, 0x16, 0xda, 0xf3, 0x39, 0x54, 0x33, 0xca, 0xd0,
	0x9e, 0x16, 0x94, 0xd3, 0x2c, 0xd4, 0x91, 0x37, 0x35, 0x28, 0xdd, 0x35, 0x7e, 0x20, 0xb0, 0x83,
	0x27, 0xe0, 0xfe, 0xfe, 0xcc, 0xc8, 0x0a, 0xb7, 0x91, 0x2d, 0x54, 0x73, 0x04, 0xbb, 0xb9, 0x5c,
	0x50, 0x51, 0x7b, 0xae, 0xe0, 0x54, 0x52, 0x64, 0x4e, 0x70, 0x5a, 0xef, 0x5f, 0x09, 0xd4, 0x92,
	0x0e, 0xa5, 0x38, 0x7a, 0x57, 0x55, 0xca, 0xb1, 0x2b, 0x2c, 0x3e, 0x76, 0x37, 0x14, 0xb6, 0x78,
	0xef, 0xc2, 0xee, 0xc1, 0x9b, 0x1a, 0x09, 0xd8, 0x01, 0xb7, 0x80, 0x7e, 0xc9, 0x99, 0x2b, 0x2e,
	0xac, 0x0b, 0x6e, 0x8d, 0x50, 0x59, 0xdc, 0x97, 0x33, 0xab, 0x09, 0xf8, 0xe0, 0xef, 0x32, 0x94,
	0xce, 0x06, 0xf1, 0x05, 0x92, 0x32, 0x80, 0xd9, 0xed, 0x88, 0x26, 0x37, 0xbb, 0xdc, 0xcd, 0xac,
	0xbe, 0x9b, 0x5b, 0x47, 0xda, 0xe6, 0xf7, 0xbf, 0xff, 0xf5, 0x73, 0xa1, 0x6e, 0x6c, 0x77, 0x5f,
	0x7e, 0x84, 0x77, 0xd2, 0xae, 0xeb, 0x44, 0xe2, 0x4a, 0xc2, 0x7a, 0xa4, 0xfd, 0x21, 0xa1, 0xdf,
	0x40, 0x79, 0x7a, 0x8f, 0xa1, 0x5b, 0x73, 0xd7, 0x9a, 0x24, 0xfc, 0xb6, 0xf6, 0xb2, 0x63, 0xec,
	0xcb, 0xe0, 0x35, 0xa3, 0xaa, 0x04, 0x1f, 0xf2, 0x24, 0x76, 0x8f, 0xb4, 0xa9, 0x05, 0xab, 0xca,
	0x50, 0xa7, 0xbb, 0x37, 0xdc, 0x3b, 0xea, 0xb5, 0xfc, 0x06, 0x32, 0x3c, 0x90, 0x0c, 0x7b, 0xc6,
	0x8e, 0xc2, 0x60, 0x49, 0x9c, 0x4a, 0xa2, 0x8c, 0x73, 0x24, 0xc9, 0x5f, 0x1a, 0x90, 0x44, 0x37,
	0xf9, 0x75, 0x24, 0xb6, 0xc4, 0xa9, 0x24, 0xca, 0xfc, 0x44, 0x92, 0xfc, 0x88, 0x47, 0x12, 0xdd,
	0xa8, 0xd5, 0x91, 0x5c, 0x4a, 0x5c, 0x4a, 0xf2, 0x2d, 0xc0, 0x6c, 0x74, 0x62, 0xa9, 0x73, 0xe3,
	0x19, 0x4b, 0xad, 0x99, 0xb1, 0xba, 0x52, 0x07, 0x31, 0x4c, 0x55, 0xa1, 0x34, 0x66, 0x54, 0x91,
	0x9f, 0x1c, 0xa8, 0x42, 0xd3, 0xc3, 0xb5, 0x2a, 0x98, 0x35, 0xba, 0x44, 0x1c, 0x92, 0x28, 0xed,
	0x0d, 0x49, 0xf2, 0xad, 0x1c, 0x49, 0x34, 0x9d, 0x50, 0x4b, 0x32, 0xe4, 0x42, 0x25, 0x89, 0x60,
	0x63, 0xae, 0xeb, 0xd0, 0x3d, 0xf4, 0x45, 0xd7, 0x17, 0xeb, 0x0d, 0xfd, 0x26, 0x12, 0x3e, 0x94,
	0x84, 0x6f, 0x1b, 0xf5, 0x8c, 0x73, 0x12, 0xab, 0x92, 0x7e, 0x07, 0x9b, 0xb9, 0xf3, 0x4d, 0xdf,
	0x52, 0x2a, 0x9e, 0x6f, 0x5d, 0xf5, 0xfd, 0x9b, 0xb6, 0x91, 0xfa, 0x91, 0xa4, 0x7e, 0x60, 0x34,
	0x72, 0x3f, 0x0b, 0x66, 0x8d, 0x6c, 0x44, 0xa3, 0xad, 0x4a, 0xa7, 0x40, 0x5b, 0xf3, 0x1d, 0x05,
	0x6d, 0xd5, 0x34, 0x15, 0xad, 0xad, 0x17, 0x33, 0x5c, 0x8f, 0xb4, 0xcf, 0x4b, 0xf2, 0x7f, 0xd1,
	0x8f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x50, 0x0f, 0xab, 0x41, 0xc2, 0x0e, 0x00, 0x00,
}
